//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Timbox
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:WashOut", ConfigurationName="Timbox.timbrado_cfdi40_port")]
    public interface timbrado_cfdi40_port
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="timbrar_cfdi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="timbrar_cfdi_result")]
        System.Threading.Tasks.Task<Timbox.timbrar_cfdi_result> timbrar_cfdiAsync(string username, string password, string sxml);
        
        [System.ServiceModel.OperationContractAttribute(Action="timbrar_cfdi_qr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="timbrar_cfdi_qr_result")]
        System.Threading.Tasks.Task<Timbox.timbrar_cfdi_qr_result> timbrar_cfdi_qrAsync(string username, string password, string sxml);
        
        [System.ServiceModel.OperationContractAttribute(Action="timbrar_multirfc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="timbrar_multirfc_result")]
        System.Threading.Tasks.Task<Timbox.timbrar_multirfc_result> timbrar_multirfcAsync(string username, string password, string rfc, string sxml);
        
        [System.ServiceModel.OperationContractAttribute(Action="timbrar_cfdi_referencia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="timbrar_cfdi_referencia_result")]
        System.Threading.Tasks.Task<Timbox.timbrar_cfdi_referencia_result> timbrar_cfdi_referenciaAsync(string username, string password, string sxml, string external_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="timbrar_zip", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="timbrar_zip_result")]
        System.Threading.Tasks.Task<Timbox.timbrar_zip_result> timbrar_zipAsync(string username, string password, string zipbase64);
        
        [System.ServiceModel.OperationContractAttribute(Action="buscar_cfdis", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="buscar_cfdis_result")]
        System.Threading.Tasks.Task<Timbox.buscar_cfdis_result> buscar_cfdisAsync(string username, string password, Timbox.parametros_cfdis parametros_cfdis);
        
        [System.ServiceModel.OperationContractAttribute(Action="buscar_acuse_recepcion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="buscar_acuse_recepcion_result")]
        System.Threading.Tasks.Task<Timbox.buscar_acuse_recepcion_result> buscar_acuse_recepcionAsync(string username, string password, Timbox.parametros_acuse parametros_acuse);
        
        [System.ServiceModel.OperationContractAttribute(Action="recuperar_comprobante", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="recuperar_comprobante_result")]
        System.Threading.Tasks.Task<Timbox.recuperar_comprobante_result> recuperar_comprobanteAsync(string username, string password, Timbox.recuperar uuid);
        
        [System.ServiceModel.OperationContractAttribute(Action="recuperar_comprobante_referencia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="recuperar_comprobante_referencia")]
        System.Threading.Tasks.Task<Timbox.recuperar_comprobante_referencia> recuperar_comprobante_referenciaAsync(string username, string password, Timbox.external_id external_ids);
        
        [System.ServiceModel.OperationContractAttribute(Action="obtener_consumo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="obtener_consumo_result")]
        System.Threading.Tasks.Task<Timbox.obtener_consumo_result> obtener_consumoAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="consulta_rfc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="consulta_rfc_result")]
        System.Threading.Tasks.Task<Timbox.consulta_rfc_result> consulta_rfcAsync(string username, string password, string rfc);
        
        [System.ServiceModel.OperationContractAttribute(Action="consulta_lco", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="consulta_lco_result")]
        System.Threading.Tasks.Task<Timbox.consulta_lco_result> consulta_lcoAsync(string username, string password, string rfc);
        
        [System.ServiceModel.OperationContractAttribute(Action="timbrar_cfdi_roma", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="timbrar_cfdi_roma_result")]
        System.Threading.Tasks.Task<Timbox.timbrar_cfdi_roma_result> timbrar_cfdi_romaAsync(string username, string password, string rfc_emisor, string tipo_comprobante, string serie, string folio, string sxml);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class timbrar_cfdi_result
    {
        
        private string xmlField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string xml
        {
            get
            {
                return this.xmlField;
            }
            set
            {
                this.xmlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class timbrar_cfdi_roma_result
    {
        
        private string xmlField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string xml
        {
            get
            {
                return this.xmlField;
            }
            set
            {
                this.xmlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class consulta_lco_result
    {
        
        private string codigoField;
        
        private string statusField;
        
        private string informacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string informacion
        {
            get
            {
                return this.informacionField;
            }
            set
            {
                this.informacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class consulta_rfc_result
    {
        
        private string codigoField;
        
        private string statusField;
        
        private string informacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigo
        {
            get
            {
                return this.codigoField;
            }
            set
            {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string informacion
        {
            get
            {
                return this.informacionField;
            }
            set
            {
                this.informacionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class obtener_consumo_result
    {
        
        private string plan_actualField;
        
        private System.Nullable<int> creditos_asignadosField;
        
        private System.Nullable<int> creditos_usadosField;
        
        private string inicio_planField;
        
        private string fin_planField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string plan_actual
        {
            get
            {
                return this.plan_actualField;
            }
            set
            {
                this.plan_actualField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> creditos_asignados
        {
            get
            {
                return this.creditos_asignadosField;
            }
            set
            {
                this.creditos_asignadosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<int> creditos_usados
        {
            get
            {
                return this.creditos_usadosField;
            }
            set
            {
                this.creditos_usadosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string inicio_plan
        {
            get
            {
                return this.inicio_planField;
            }
            set
            {
                this.inicio_planField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fin_plan
        {
            get
            {
                return this.fin_planField;
            }
            set
            {
                this.fin_planField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class recuperar_comprobante_referencia
    {
        
        private string estatusField;
        
        private string cantidadField;
        
        private string comprobantesField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string estatus
        {
            get
            {
                return this.estatusField;
            }
            set
            {
                this.estatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cantidad
        {
            get
            {
                return this.cantidadField;
            }
            set
            {
                this.cantidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string comprobantes
        {
            get
            {
                return this.comprobantesField;
            }
            set
            {
                this.comprobantesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class external_id
    {
        
        private string[] external_id1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute("external_id", IsNullable=true)]
        public string[] external_id1
        {
            get
            {
                return this.external_id1Field;
            }
            set
            {
                this.external_id1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class recuperar_comprobante_result
    {
        
        private string estatusField;
        
        private string cantidadField;
        
        private string comprobantesField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string estatus
        {
            get
            {
                return this.estatusField;
            }
            set
            {
                this.estatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cantidad
        {
            get
            {
                return this.cantidadField;
            }
            set
            {
                this.cantidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string comprobantes
        {
            get
            {
                return this.comprobantesField;
            }
            set
            {
                this.comprobantesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class buscar_acuse_recepcion_result
    {
        
        private string acusesField;
        
        private string uuids_erroneosField;
        
        private string uuids_no_encontradosField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string acuses
        {
            get
            {
                return this.acusesField;
            }
            set
            {
                this.acusesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string uuids_erroneos
        {
            get
            {
                return this.uuids_erroneosField;
            }
            set
            {
                this.uuids_erroneosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string uuids_no_encontrados
        {
            get
            {
                return this.uuids_no_encontradosField;
            }
            set
            {
                this.uuids_no_encontradosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class Comprobante
    {
        
        private string uuidField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string uuid
        {
            get
            {
                return this.uuidField;
            }
            set
            {
                this.uuidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class recuperar
    {
        
        private Comprobante[] comprobanteField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public Comprobante[] Comprobante
        {
            get
            {
                return this.comprobanteField;
            }
            set
            {
                this.comprobanteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class parametros_acuse
    {
        
        private recuperar uuidsField;
        
        private string fecha_timbrado_inicioField;
        
        private string fecha_timbrado_finField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public recuperar uuids
        {
            get
            {
                return this.uuidsField;
            }
            set
            {
                this.uuidsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fecha_timbrado_inicio
        {
            get
            {
                return this.fecha_timbrado_inicioField;
            }
            set
            {
                this.fecha_timbrado_inicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fecha_timbrado_fin
        {
            get
            {
                return this.fecha_timbrado_finField;
            }
            set
            {
                this.fecha_timbrado_finField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class buscar_cfdis_result
    {
        
        private string estatusField;
        
        private string cantidadField;
        
        private string comprobantesField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string estatus
        {
            get
            {
                return this.estatusField;
            }
            set
            {
                this.estatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cantidad
        {
            get
            {
                return this.cantidadField;
            }
            set
            {
                this.cantidadField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string comprobantes
        {
            get
            {
                return this.comprobantesField;
            }
            set
            {
                this.comprobantesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class parametros_cfdis
    {
        
        private string rfc_emisorField;
        
        private string rfc_receptorField;
        
        private string fecha_emision_inicioField;
        
        private string fecha_emision_finField;
        
        private string fecha_timbrado_inicioField;
        
        private string fecha_timbrado_finField;
        
        private string canceladoField;
        
        private string external_idField;
        
        private string uuidField;
        
        private string folioField;
        
        private string serieField;
        
        private string limitField;
        
        private string offsetField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string rfc_emisor
        {
            get
            {
                return this.rfc_emisorField;
            }
            set
            {
                this.rfc_emisorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string rfc_receptor
        {
            get
            {
                return this.rfc_receptorField;
            }
            set
            {
                this.rfc_receptorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fecha_emision_inicio
        {
            get
            {
                return this.fecha_emision_inicioField;
            }
            set
            {
                this.fecha_emision_inicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fecha_emision_fin
        {
            get
            {
                return this.fecha_emision_finField;
            }
            set
            {
                this.fecha_emision_finField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fecha_timbrado_inicio
        {
            get
            {
                return this.fecha_timbrado_inicioField;
            }
            set
            {
                this.fecha_timbrado_inicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fecha_timbrado_fin
        {
            get
            {
                return this.fecha_timbrado_finField;
            }
            set
            {
                this.fecha_timbrado_finField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cancelado
        {
            get
            {
                return this.canceladoField;
            }
            set
            {
                this.canceladoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string external_id
        {
            get
            {
                return this.external_idField;
            }
            set
            {
                this.external_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string uuid
        {
            get
            {
                return this.uuidField;
            }
            set
            {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string folio
        {
            get
            {
                return this.folioField;
            }
            set
            {
                this.folioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string serie
        {
            get
            {
                return this.serieField;
            }
            set
            {
                this.serieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string limit
        {
            get
            {
                return this.limitField;
            }
            set
            {
                this.limitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string offset
        {
            get
            {
                return this.offsetField;
            }
            set
            {
                this.offsetField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class timbrar_zip_result
    {
        
        private string xmlField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string xml
        {
            get
            {
                return this.xmlField;
            }
            set
            {
                this.xmlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class timbrar_cfdi_referencia_result
    {
        
        private string xmlField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string xml
        {
            get
            {
                return this.xmlField;
            }
            set
            {
                this.xmlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class timbrar_multirfc_result
    {
        
        private string xmlField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string xml
        {
            get
            {
                return this.xmlField;
            }
            set
            {
                this.xmlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:WashOut")]
    public partial class timbrar_cfdi_qr_result
    {
        
        private string xmlField;
        
        private string qr64Field;
        
        private string uuidField;
        
        private string rfc_emisorField;
        
        private string notaField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string xml
        {
            get
            {
                return this.xmlField;
            }
            set
            {
                this.xmlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string qr64
        {
            get
            {
                return this.qr64Field;
            }
            set
            {
                this.qr64Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string uuid
        {
            get
            {
                return this.uuidField;
            }
            set
            {
                this.uuidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string rfc_emisor
        {
            get
            {
                return this.rfc_emisorField;
            }
            set
            {
                this.rfc_emisorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nota
        {
            get
            {
                return this.notaField;
            }
            set
            {
                this.notaField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface timbrado_cfdi40_portChannel : Timbox.timbrado_cfdi40_port, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class timbrado_cfdi40_portClient : System.ServiceModel.ClientBase<Timbox.timbrado_cfdi40_port>, Timbox.timbrado_cfdi40_port
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public timbrado_cfdi40_portClient() : 
                base(timbrado_cfdi40_portClient.GetDefaultBinding(), timbrado_cfdi40_portClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.timbrado_cfdi40_port.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public timbrado_cfdi40_portClient(EndpointConfiguration endpointConfiguration) : 
                base(timbrado_cfdi40_portClient.GetBindingForEndpoint(endpointConfiguration), timbrado_cfdi40_portClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public timbrado_cfdi40_portClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(timbrado_cfdi40_portClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public timbrado_cfdi40_portClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(timbrado_cfdi40_portClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public timbrado_cfdi40_portClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Timbox.timbrar_cfdi_result> timbrar_cfdiAsync(string username, string password, string sxml)
        {
            return base.Channel.timbrar_cfdiAsync(username, password, sxml);
        }
        
        public System.Threading.Tasks.Task<Timbox.timbrar_cfdi_qr_result> timbrar_cfdi_qrAsync(string username, string password, string sxml)
        {
            return base.Channel.timbrar_cfdi_qrAsync(username, password, sxml);
        }
        
        public System.Threading.Tasks.Task<Timbox.timbrar_multirfc_result> timbrar_multirfcAsync(string username, string password, string rfc, string sxml)
        {
            return base.Channel.timbrar_multirfcAsync(username, password, rfc, sxml);
        }
        
        public System.Threading.Tasks.Task<Timbox.timbrar_cfdi_referencia_result> timbrar_cfdi_referenciaAsync(string username, string password, string sxml, string external_id)
        {
            return base.Channel.timbrar_cfdi_referenciaAsync(username, password, sxml, external_id);
        }
        
        public System.Threading.Tasks.Task<Timbox.timbrar_zip_result> timbrar_zipAsync(string username, string password, string zipbase64)
        {
            return base.Channel.timbrar_zipAsync(username, password, zipbase64);
        }
        
        public System.Threading.Tasks.Task<Timbox.buscar_cfdis_result> buscar_cfdisAsync(string username, string password, Timbox.parametros_cfdis parametros_cfdis)
        {
            return base.Channel.buscar_cfdisAsync(username, password, parametros_cfdis);
        }
        
        public System.Threading.Tasks.Task<Timbox.buscar_acuse_recepcion_result> buscar_acuse_recepcionAsync(string username, string password, Timbox.parametros_acuse parametros_acuse)
        {
            return base.Channel.buscar_acuse_recepcionAsync(username, password, parametros_acuse);
        }
        
        public System.Threading.Tasks.Task<Timbox.recuperar_comprobante_result> recuperar_comprobanteAsync(string username, string password, Timbox.recuperar uuid)
        {
            return base.Channel.recuperar_comprobanteAsync(username, password, uuid);
        }
        
        public System.Threading.Tasks.Task<Timbox.recuperar_comprobante_referencia> recuperar_comprobante_referenciaAsync(string username, string password, Timbox.external_id external_ids)
        {
            return base.Channel.recuperar_comprobante_referenciaAsync(username, password, external_ids);
        }
        
        public System.Threading.Tasks.Task<Timbox.obtener_consumo_result> obtener_consumoAsync(string username, string password)
        {
            return base.Channel.obtener_consumoAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<Timbox.consulta_rfc_result> consulta_rfcAsync(string username, string password, string rfc)
        {
            return base.Channel.consulta_rfcAsync(username, password, rfc);
        }
        
        public System.Threading.Tasks.Task<Timbox.consulta_lco_result> consulta_lcoAsync(string username, string password, string rfc)
        {
            return base.Channel.consulta_lcoAsync(username, password, rfc);
        }
        
        public System.Threading.Tasks.Task<Timbox.timbrar_cfdi_roma_result> timbrar_cfdi_romaAsync(string username, string password, string rfc_emisor, string tipo_comprobante, string serie, string folio, string sxml)
        {
            return base.Channel.timbrar_cfdi_romaAsync(username, password, rfc_emisor, tipo_comprobante, serie, folio, sxml);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.timbrado_cfdi40_port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.timbrado_cfdi40_port))
            {
                return new System.ServiceModel.EndpointAddress("https://sistema.timbox.com.mx/timbrado_cfdi40/action");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return timbrado_cfdi40_portClient.GetBindingForEndpoint(EndpointConfiguration.timbrado_cfdi40_port);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return timbrado_cfdi40_portClient.GetEndpointAddress(EndpointConfiguration.timbrado_cfdi40_port);
        }
        
        public enum EndpointConfiguration
        {
            
            timbrado_cfdi40_port,
        }
    }
}
